=== chungote/pyramus/trunk/PyramusUpdater/schema/UpdaterSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- 
    Root Node (updates) 
    
    may contain nodes createTables, dropTables and alterTables
  -->
  
  <xs:element name="update">
    <xs:complexType>
      <xs:sequence>
        <!-- 
          createTables node
          
          contains 1..* table nodes
         -->
        <xs:element name="createTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="fields" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="foreignKeys" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                  <xs:attribute name="primaryKeys" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <!-- 
          dropTables node
          
          contains 1..* table nodes
        -->
        <xs:element name="dropTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="alterTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="addFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="addForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
</xs:schema>

=== chungote/pyramus/Pyramus/updates/3.004/100929_tags.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>
    <table name="Tag" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="true"/>
        <field name="text" type="java.lang.String" length="255" nullable="false"/>
      </fields>
    </table>
    <table name="__CourseTags" primaryKeys="course,tag">
      <fields>
        <field name="course" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="course" referencedColumns="id" referencedTable="Course"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__HelpItemTags" primaryKeys="helpItem,tag">
      <fields>
        <field name="helpItem" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="helpItem" referencedColumns="id" referencedTable="HelpItem"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__ModuleTags" primaryKeys="module,tag">
      <fields>
        <field name="module" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="module" referencedColumns="id" referencedTable="Module"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__ProjectTags" primaryKeys="project,tag">
      <fields>
        <field name="project" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="project" referencedColumns="id" referencedTable="Project"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__ResourceTags" primaryKeys="resource,tag">
      <fields>
        <field name="resource" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="resource" referencedColumns="id" referencedTable="Resource"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__SchoolTags" primaryKeys="school,tag">
      <fields>
        <field name="school" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="school" referencedColumns="id" referencedTable="School"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__StudentProjectTags" primaryKeys="studentProject,tag">
      <fields>
        <field name="studentProject" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="studentProject" referencedColumns="id" referencedTable="StudentProject"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__StudentGroupTags" primaryKeys="studentGroup,tag">
      <fields>
        <field name="studentGroup" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="studentGroup" referencedColumns="id" referencedTable="StudentGroup"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__StudentTags" primaryKeys="student,tag">
      <fields>
        <field name="student" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="student" referencedColumns="id" referencedTable="Student"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
    <table name="__UserTags" primaryKeys="user,tag">
      <fields>
        <field name="user" type="java.lang.Long" nullable="false"/>
        <field name="tag" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="user" referencedColumns="id" referencedTable="User"/>
        <key columns="tag" referencedColumns="id" referencedTable="Tag"/>
      </foreignKeys>
    </table>
  </createTables>
</update>

=== chungote/pyramus/trunk/Pyramus/updates/4.006/011209_transfercredittemplates.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table primaryKeys="id" name="TransferCreditTemplate">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="version" type="java.lang.Long" nullable="false" unique="false" />
        <field name="name" type="java.lang.String" nullable="false" unique="false" />
      </fields>
    </table>
    <table primaryKeys="id" name="TransferCreditTemplateCourse">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="version" type="java.lang.Long" nullable="false" unique="false" />
        <field name="courseName" type="java.lang.String" nullable="false" unique="false" />
        <field name="courseNumber" type="java.lang.Integer" nullable="true" unique="false" />
        <field name="optionality" type="java.lang.Integer" nullable="false" unique="false" />
        <field name="courseLength" type="java.lang.Long" nullable="true" unique="false" />
        <field name="subject" type="java.lang.Long" nullable="true" unique="false" />
        <field name="transferCreditTemplate" type="java.lang.Long" nullable="true" unique="false" />
        <field name="indexColumn" type="java.lang.Integer" nullable="true" unique="false" />
      </fields>
      <foreignKeys>
        <key referencedColumns="id" columns="subject" referencedTable="Subject"/>
        <key referencedColumns="id" columns="transferCreditTemplate" referencedTable="TransferCreditTemplate"/>
        <key referencedColumns="id" columns="courseLength" referencedTable="EducationalLength"/>
      </foreignKeys>
    </table>
  </createTables>

</update>

=== chungote/pyramus/tags/version 0.6.2/Pyramus/updates/3.003/100929_reportcategories.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>  
    <table name="ReportCategory" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="indexColumn" type="java.lang.Integer"/>
        <field name="name" type="java.lang.String" length="255" nullable="false"/>
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="Report">
      <addFields>
        <field name="category" type="java.lang.Long"/>
      </addFields>
      <addForeignKeys>
        <key name="FK91B1415426DDD5AE" columns="category" referencedColumns="id" referencedTable="ReportCategory"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/trunk/Pyramus/updates/18.002/110616_coursebase_enrolment.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <alterTables>
    <table name="CourseBase">
      <addFields>
        <field name="maxParticipantCount" type="java.lang.Long" nullable="true" unique="false" />
      </addFields>
    </table>

    <table name="Course">
      <addFields>
        <field name="enrolmentTimeEnd" type="Types.TIMESTAMP" nullable="true" unique="false" />
      </addFields>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/trunk/Pyramus/updates/21.004/120522_courseassessmentrequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table primaryKeys="id" name="CourseAssessmentRequest">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="courseStudent" type="java.lang.Long" nullable="true" unique="false" />
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="requestText" type="java.lang.String" length="1073741824" nullable="false"/> 
        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
      </fields>
      <foreignKeys>
        <key referencedColumns="id" columns="courseStudent" referencedTable="CourseStudent"/>
      </foreignKeys>
    </table>
  </createTables>

</update>

=== chungote/pyramus/trunk/Pyramus/updates/16.001/110519_subjecteducationtype.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2010/pyramus/UpdaterSchema.xsd">
  
  <alterTables>
    <table name="StudyProgrammeCategory">
      <addFields>
        <field name="educationType" type="java.lang.Integer" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key columns="educationType" referencedColumns="id" referencedTable="EducationType"/>
      </addForeignKeys>
    </table>

    <table name="Subject">
      <addFields>
        <field name="educationType" type="java.lang.Integer" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key columns="educationType" referencedColumns="id" referencedTable="EducationType"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/trunk/Pyramus/updates/6.001/110117_schoolfield.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>
    <table name="SchoolField" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="name" type="java.lang.String" nullable="false" unique="false" />
        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="School">
      <addFields>
        <field name="field" type="java.lang.Long" nullable="true"/>
      </addFields>

      <addForeignKeys>
        <key columns="field" referencedColumns="id" referencedTable="SchoolField" />
      </addForeignKeys>
    </table>
  </alterTables>
</update>

=== chungote/pyramus/tags/version 0.6.1/Pyramus/updates/4.003/011208_optionality.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <alterTables>
    <table name="CourseStudent">
      <addFields>
        <field name="optionality" type="java.lang.Integer" nullable="true" unique="false" />
      </addFields>
    </table>
    
    <table name="TransferCredit">
      <addFields>
        <field name="optionality" type="java.lang.Integer" nullable="true" unique="false" />
      </addFields>
    </table>
  </alterTables>

</update>
