=== chungote/pyramus/trunk/PyramusUpdater/schema/UpdaterSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- 
    Root Node (updates) 
    
    may contain nodes createTables, dropTables and alterTables
  -->
  
  <xs:element name="update">
    <xs:complexType>
      <xs:sequence>
        <!-- 
          createTables node
          
          contains 1..* table nodes
         -->
        <xs:element name="createTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="fields" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="foreignKeys" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                  <xs:attribute name="primaryKeys" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <!-- 
          dropTables node
          
          contains 1..* table nodes
        -->
        <xs:element name="dropTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="alterTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="addFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="addForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
</xs:schema>

=== chungote/pyramus/Pyramus/updates/15.001/110506_coursedescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>
    <table name="CourseDescriptionCategory" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="true"/>
        <field name="name" type="java.lang.String" length="255" nullable="false"/>
        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
      </fields>
    </table>
    
    <table name="CourseDescription" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="true"/>
        <field name="courseBase" type="java.lang.Long"/>
        <field name="category" type="java.lang.Long"/>
        <field name="description" type="java.lang.String" length="2147483647"/>
      </fields>
      <foreignKeys>
        <key columns="courseBase" referencedColumns="id" referencedTable="CourseBase"/>
        <key columns="category" referencedColumns="id" referencedTable="CourseDescriptionCategory"/>
      </foreignKeys>
    </table>
  </createTables>
</update>

=== chungote/pyramus/Pyramus/updates/16.001/110519_subjecteducationtype.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <alterTables>
    <table name="StudyProgrammeCategory">
      <addFields>
        <field name="educationType" type="java.lang.Long" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key columns="educationType" referencedColumns="id" referencedTable="EducationType"/>
      </addForeignKeys>
    </table>

    <table name="Subject">
      <addFields>
        <field name="educationType" type="java.lang.Long" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key columns="educationType" referencedColumns="id" referencedTable="EducationType"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/Pyramus/updates/21.002/120508_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="FileType" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="name" type="java.lang.String" length="255" nullable="false"/> 
        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
      </fields>
    </table>

    <table name="File" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />

        <field name="name" type="java.lang.String" length="255" nullable="false"/> 
        <field name="fileName" type="java.lang.String" length="255" nullable="false"/> 
        <field name="fileType" type="java.lang.Long" nullable="true" unique="false" />
        <field name="contentType" type="java.lang.String" nullable="true" unique="false" />
        <field name="data" type="java.sql.Blob" nullable="true" unique="false" length="1073741824"/>

        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="creator" type="java.lang.Long" nullable="true" unique="false" />
        <field name="lastModified" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="lastModifier" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
    </table>

    <table name="StudentFile" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="student" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="File">
      <addForeignKeys>
        <key columns="fileType" referencedColumns="id" referencedTable="FileType" />
        <key columns="creator" referencedColumns="id" referencedTable="User" />
        <key columns="lastModifier" referencedColumns="id" referencedTable="User" />
      </addForeignKeys>
    </table>
    
    <table name="StudentFile">
      <addForeignKeys>
        <key columns="id" referencedColumns="id" referencedTable="File" />
        <key columns="student" referencedColumns="id" referencedTable="Student" />
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/Pyramus/updates/21.001/120403_creditlink.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="CreditLink" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />

        <field name="credit" type="java.lang.Long" nullable="false" unique="false" />
        <field name="student" type="java.lang.Long" nullable="true" unique="false" />

        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="creator" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="CreditLink">
      <addForeignKeys>
        <key columns="credit" referencedColumns="id" referencedTable="Credit" />
        <key columns="student" referencedColumns="id" referencedTable="Student" />
        <key columns="creator" referencedColumns="id" referencedTable="User" />
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/Pyramus/updates/3.009/101027_contactentry_comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>
    <table name="StudentContactLogEntryComment" primaryKeys="id">
      <fields>
        <field name="entry" type="java.lang.Long" nullable="false" unique="false" />
        <field name="commentDate" type="Types.TIMESTAMP" nullable="true" unique="false" />
        <field name="text" type="java.lang.String" nullable="true" unique="false" />
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="archived" type="java.lang.Boolean" nullable="false" unique="false" />
        <field name="creatorName" type="java.lang.String" nullable="true" unique="false" />
        <field name="version" type="java.lang.Long" nullable="false" unique="false" />
      </fields>

      <foreignKeys>
        <key columns="entry" referencedColumns="id" referencedTable="StudentContactLogEntry" />
      </foreignKeys>
    </table>
  </createTables>
</update>

=== chungote/pyramus/trunk/Pyramus/updates/18.001/110607_projectassessment.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="ProjectAssessment" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="studentProject" type="java.lang.Long" nullable="true" />
      </fields>

      <foreignKeys>
        <key referencedColumns="id" columns="studentProject" referencedTable="StudentProject"/>
      </foreignKeys>
    </table>
  </createTables>
  
  <alterTables>
    <table name="StudentProject">
      <addFields>
        <field name="project" type="java.lang.Long" nullable="true" unique="false" />
        <field name="optionality" type="java.lang.Integer" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key referencedColumns="id" columns="project" referencedTable="Project"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/Pyramus/updates/22.002/130125_courseStudentVariable.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="CourseStudentVariable" primaryKeys="id">
      <fields>
        <field name="courseStudent" type="java.lang.Long" nullable="true" unique="false" />
        <field name="id" type="java.lang.Long" nullable="false" unique="true" />
        <field name="value" type="java.lang.String" length="1073741824" nullable="true" unique="false" />
        <field name="variableKey" type="java.lang.Long" nullable="true" unique="false" />
        <field name="version" type="java.lang.Long" nullable="false" unique="false" />
      </fields>
      <foreignKeys>
        <key columns="courseStudent" referencedColumns="id" referencedTable="CourseStudent" />
        <key columns="variableKey" referencedColumns="id" referencedTable="CourseStudentVariableKey" />
      </foreignKeys>
    </table>
    <table name="CourseStudentVariableKey" primaryKeys="id">
      <fields>
        <field name="variableName" type="java.lang.String" nullable="false" unique="false" />
        <field name="id" type="java.lang.Long" nullable="false" unique="true" />
        <field name="variableType" type="java.lang.String" nullable="true" unique="false" />
        <field name="userEditable" type="java.lang.Boolean" nullable="false" unique="false" />
        <field name="variableKey" type="java.lang.String" nullable="false" unique="false" />
        <field name="version" type="java.lang.Long" nullable="false" unique="false" />
      </fields>
    </table>
  </createTables>
</update>

=== chungote/pyramus/Pyramus/updates/3.008/101008_coursecomponentresources.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  
  <createTables>
    <table name="CourseComponentResource" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="usagePercent" type="java.lang.Double" nullable="false"/>
        <field name="courseComponent" type="java.lang.Long"/>
        <field name="resource" type="java.lang.Long"/>
      </fields>
      <foreignKeys>
        <key columns="courseComponent" referencedColumns="id" referencedTable="CourseComponent"/>
        <key columns="resource" referencedColumns="id" referencedTable="Resource"/>
      </foreignKeys>
    </table>
  </createTables>
</update>
