=== chungote/pyramus/trunk/PyramusUpdater/schema/UpdaterSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- 
    Root Node (updates) 
    
    may contain nodes createTables, dropTables and alterTables
  -->
  
  <xs:element name="update">
    <xs:complexType>
      <xs:sequence>
        <!-- 
          createTables node
          
          contains 1..* table nodes
         -->
        <xs:element name="createTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="fields" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="foreignKeys" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                  <xs:attribute name="primaryKeys" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <!-- 
          dropTables node
          
          contains 1..* table nodes
        -->
        <xs:element name="dropTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="alterTables" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="addFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="length" type="xs:integer"/>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                              <xs:attribute name="nullable" type="xs:boolean"/>
                              <xs:attribute name="type" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropFields">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="addForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="columns" use="required" type="xs:NCName"/>
                              <xs:attribute name="name" type="xs:NCName"/>
                              <xs:attribute name="referencedColumns" use="required" type="xs:NCName"/>
                              <xs:attribute name="referencedTable" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dropForeignKeys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" use="required" type="xs:NCName"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
</xs:schema>

=== chungote/pyramus/trunk/Pyramus/updates/4.001/101126_studentprojectcourse.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="StudentProjectCourse" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="course" type="java.lang.Long" nullable="true" unique="false" />
        <field name="studentProject" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="StudentProjectCourse">
      <addForeignKeys>
        <key columns="studentProject" referencedColumns="id" referencedTable="StudentProject" />
        <key columns="course" referencedColumns="id" referencedTable="Course" />
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/tags/version 0.6.4/Pyramus/updates/21.003/120516_reportcontext.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="ReportContext" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="report" type="java.lang.Long" nullable="true" unique="false" />
        <field name="context" type="java.lang.String" length="255" nullable="false"/> 
      </fields>
      <foreignKeys>
        <key columns="report" referencedColumns="id" referencedTable="Report" />
      </foreignKeys>
    </table>
  </createTables>

  <sql>insert into ReportContext (id, report, context) select id, id, 'Common' from Report</sql> 
  <sql>insert into hibernate_sequences (sequence_name, sequence_next_hi_value) select 'ReportContext', coalesce(max(id) + 1, 1) from ReportContext</sql>
</update>

=== chungote/pyramus/tags/version 0.6.1/Pyramus/updates/3.002/100927_help.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
  <createTables>
    <table name="HelpItem" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="indexColumn" type="java.lang.Integer" nullable="false"/>
        <field name="parent" type="java.lang.Long"/>
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="creator" type="java.lang.Long" nullable="true" unique="false" />
        <field name="lastModified" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="lastModifier" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
      <foreignKeys>
        <key name="FKD4C29A1476DFD82D" columns="lastModifier" referencedColumns="id" referencedTable="User"/>
        <key name="FKD4C29A144344B8EC" columns="creator" referencedColumns="id" referencedTable="User"/>
      </foreignKeys>
    </table>
    
    <table name="HelpItemTitle" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="item" type="java.lang.Long"/>
        <field name="locale" type="java.lang.String" length="255" nullable="false"/>
        <field name="title" type="java.lang.String" length="255" nullable="false"/>
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="creator" type="java.lang.Long" nullable="true" unique="false" />
        <field name="lastModified" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="lastModifier" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
      <foreignKeys>
        <key name="FKD4C29A148774E157" columns="item" referencedColumns="id" referencedTable="HelpItem"/>
        <key name="FKC5BFC4A4E1463B97" columns="lastModifier" referencedColumns="id" referencedTable="User"/>
        <key name="FKC5BFC4A44344B8EC" columns="creator" referencedColumns="id" referencedTable="User"/>
      </foreignKeys>
    </table>
    
    <table name="HelpFolder" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key name="FKA9227F2F42CE482D" columns="id" referencedColumns="id" referencedTable="HelpItem"/>
      </foreignKeys>
    </table>
    
    <table name="HelpPage" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key name="FKD4C5819042CE482D" columns="id" referencedColumns="id" referencedTable="HelpItem"/>
      </foreignKeys>
    </table>
    
    <table name="HelpPageContent" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="page" type="java.lang.Long"/>
        <field name="locale" type="java.lang.String" length="255" nullable="false"/>
        <field name="content" type="java.lang.String" length="1073741824" nullable="false"/>
        <field name="created" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="creator" type="java.lang.Long" nullable="true" unique="false" />
        <field name="lastModified" type="Types.TIMESTAMP" nullable="false" unique="false" />
        <field name="lastModifier" type="java.lang.Long" nullable="true" unique="false" />
      </fields>
      <foreignKeys>
        <key name="FKB5D068C94305851D" columns="page" referencedColumns="id" referencedTable="HelpPage"/>
        <key name="FKB5D068C9E1463B97" columns="lastModifier" referencedColumns="id" referencedTable="User"/>
        <key name="FKB5D068C94344B8EC" columns="creator" referencedColumns="id" referencedTable="User"/>
      </foreignKeys>
    </table>
  </createTables>

  <alterTables>
    <table name="HelpItem">
      <addForeignKeys>
        <key columns="parent" referencedColumns="id" referencedTable="HelpFolder"/>
      </addForeignKeys>
    </table>
  </alterTables>
</update>

=== chungote/pyramus/trunk/Pyramus/updates/1.001/100915_studentgroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="StudentGroup" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="archived" type="java.lang.Boolean" nullable="false"/>
        <field name="beginDate" type="java.util.Date"/> 
        <field name="created" type="java.util.Date" nullable="false"/>
        <field name="description" type="java.lang.String" length="1073741824"/> 
        <field name="lastModified" type="java.util.Date" nullable="false"/>
        <field name="name" type="java.lang.String" length="255" nullable="false"/> 
        <field name="creator" type="java.lang.Long"/> 
        <field name="lastModifier" type="java.lang.Long"/>
      </fields>
      <foreignKeys>
        <key name="FK75A052476DFD82D" columns="lastModifier" referencedColumns="id" referencedTable="User"/>
        <key name="FK75A05244344B8EC" columns="creator" referencedColumns="id" referencedTable="User"/>
      </foreignKeys>
    </table>
    
    <table name="StudentGroupStudent" primaryKeys="id">
      <fields>
         <field name="id" type="java.lang.Long" nullable="false"/>
         <field name="student" type="java.lang.Long"/>
         <field name="studentGroup" type="java.lang.Long"/>
      </fields>
      <foreignKeys>
        <key name="FKD427C477EE2B836F" columns="student" referencedTable="Student" referencedColumns="id"/>
        <key name="FKD427C47786F746CF" columns="studentGroup" referencedTable="StudentGroup" referencedColumns="id"/>
      </foreignKeys>
    </table>
    
    <table name="StudentGroupUser" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false"/>
        <field name="studentGroup" type="java.lang.Long"/>
        <field name="user" type="java.lang.Long"/>
      </fields>
      <foreignKeys>
        <key name="FK12F3330F86F746CF" columns="studentGroup" referencedTable="StudentGroup" referencedColumns="id"/>
        <key name="FK12F3330F62D248B" columns="user" referencedTable="User" referencedColumns="id"/>
      </foreignKeys>
    </table>
  </createTables>
  
</update>

=== chungote/pyramus/Pyramus/updates/18.003/110616_billingdetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="BillingDetails" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="personName" type="java.lang.String" nullable="true" unique="false" />
        <field name="companyName" type="java.lang.String" nullable="true" unique="false" />
        <field name="streetAddress1" type="java.lang.String" nullable="true" unique="false" />
        <field name="streetAddress2" type="java.lang.String" nullable="true" unique="false" />
        <field name="postalCode" type="java.lang.String" nullable="true" unique="false" />
        <field name="city" type="java.lang.String" nullable="true" unique="false" />
        <field name="region" type="java.lang.String" nullable="true" unique="false" />
        <field name="country" type="java.lang.String" nullable="true" unique="false" />
        <field name="phoneNumber" type="java.lang.String" nullable="true" unique="false" />
        <field name="emailAddress" type="java.lang.String" nullable="true" unique="false" />
        <field name="bic" type="java.lang.String" nullable="true" unique="false" />
        <field name="iban" type="java.lang.String" nullable="true" unique="false" />
        <field name="companyIdentifier" type="java.lang.String" nullable="true" unique="false" />
        <field name="referenceNumber" type="java.lang.String" nullable="true" unique="false" />
      </fields>
    </table>
    <table name="__UserBillingDetails" primaryKeys="user,billingDetails">
      <fields>
        <field name="user" type="java.lang.Long" nullable="false"/>
        <field name="billingDetails" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="user" referencedColumns="id" referencedTable="User"/>
        <key columns="billingDetails" referencedColumns="id" referencedTable="BillingDetails"/>
      </foreignKeys>
    </table>
    <table name="__StudentBillingDetails" primaryKeys="student,billingDetails">
      <fields>
        <field name="student" type="java.lang.Long" nullable="false"/>
        <field name="billingDetails" type="java.lang.Long" nullable="false"/>
      </fields>
      <foreignKeys>
        <key columns="student" referencedColumns="id" referencedTable="Student"/>
        <key columns="billingDetails" referencedColumns="id" referencedTable="BillingDetails"/>
      </foreignKeys>
    </table>
  </createTables>

  <alterTables>
    <table name="CourseStudent">
      <addFields>
        <field name="billingDetails" type="java.lang.Long" nullable="true" unique="false" />
      </addFields>
      <addForeignKeys>
        <key referencedColumns="id" columns="billingDetails" referencedTable="BillingDetails"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/trunk/Pyramus/updates/4.005/101215_creditstudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <alterTables>
    <table name="CourseAssessment">
      <dropForeignKeys>
        <key name="FK9833115D5475C87B"/>
      </dropForeignKeys>
    </table>
    
    <table name="Credit">
      <dropForeignKeys>
        <key name="FK78CA9719EE2B836F"/>
      </dropForeignKeys>
    </table>
  
    <table name="CourseAssessment">
      <addFields>
        <field name="courseStudent" type="java.lang.Long" nullable="true" unique="true" />
      </addFields>

      <dropFields>
        <field name="course"/>
      </dropFields>
      
      <addForeignKeys>
        <key referencedColumns="id" columns="courseStudent" referencedTable="CourseStudent"/>
      </addForeignKeys>
    </table>

    <table name="Credit">
      <dropFields>
        <field name="student"/>
      </dropFields>
    </table>

    <table name="TransferCredit">
      <addFields>
        <field name="student" type="java.lang.Long" nullable="true" unique="false" />
      </addFields>

      <addForeignKeys>
        <key referencedColumns="id" columns="student" referencedTable="Student"/>
      </addForeignKeys>
    </table>
  </alterTables>

</update>

=== chungote/pyramus/Pyramus/updates/19.001/110815_studentimage.xml
<?xml version="1.0" encoding="UTF-8"?>
<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">

  <createTables>
    <table name="StudentImage" primaryKeys="id">
      <fields>
        <field name="id" type="java.lang.Long" nullable="false" unique="false" />
        <field name="student" type="java.lang.Long" nullable="false" unique="false" />
        <field name="contentType" type="java.lang.String" nullable="true" unique="false" />
        <field name="data" type="java.sql.Blob" nullable="true" unique="false" length="1073741824"/>
      </fields>
    </table>
  </createTables>

  <alterTables>
    <table name="StudentImage">
      <addForeignKeys>
        <key columns="student" referencedColumns="id" referencedTable="Student" />
      </addForeignKeys>
    </table>
  </alterTables>

</update>
